services:
  - type: web
    name: tu-app
    env: python
    buildCommand: 
      - pip install pandas  # Instala pandas directamente
      - poetry install  # O si usas Poetry, asegurarte que instale todas las dependencias
    startCommand: python main.py
