services:
  - type: web
    name: tu-app
    env: python
    region: oregon  
    buildCommand:
      - pip install pandas  
      - pip install -r requirements.txt  
    startCommand: python main.py 