services:
  - type: web
    name: tu-app
    env: python
    buildCommand: 
      - pip install -r requirements.txt  # Si tienes un requirements.txt
      # O puedes instalar pandas directamente:
      - pip install pandas
    startCommand: python main.py
